name: nbastatsetiya
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"


dependencies:
  auto_route: ^3.2.4
  dio: ^4.0.6
  cupertino_icons: ^1.0.2

  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  grpc: ^3.0.2
  logger: ^1.1.0
  protobuf: ^2.0.1


dev_dependencies:
  auto_route_generator: ^3.2.3
  build_runner: ^2.1.8
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true

  assets:
    - assets/
